//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uAdd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uAdd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabelText {
            get {
                return ResourceManager.GetString("AboutLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category big font.
        /// </summary>
        public static string AddSettingsBigFontCategory {
            get {
                return ResourceManager.GetString("AddSettingsBigFontCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category bold font.
        /// </summary>
        public static string AddSettingsBoldFontCategory {
            get {
                return ResourceManager.GetString("AddSettingsBoldFontCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry on failed adding.
        /// </summary>
        public static string AddSettingsFailedRetries {
            get {
                return ResourceManager.GetString("AddSettingsFailedRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not add default category in categories list.
        /// </summary>
        public static string AddSettingsNotAddDefaultCategory {
            get {
                return ResourceManager.GetString("AddSettingsNotAddDefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not allow an empty category.
        /// </summary>
        public static string AddSettingsNotAllowEmptyCategory {
            get {
                return ResourceManager.GetString("AddSettingsNotAllowEmptyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorHeaderText {
            get {
                return ResourceManager.GetString("AuthorHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;default&gt;.
        /// </summary>
        public static string CategoriesDefaultValue {
            get {
                return ResourceManager.GetString("CategoriesDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string CategoryNameText {
            get {
                return ResourceManager.GetString("CategoryNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all files.
        /// </summary>
        public static string CommandCheckAllFiles {
            get {
                return ResourceManager.GetString("CommandCheckAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck all files.
        /// </summary>
        public static string CommandUnCheckAllFiles {
            get {
                return ResourceManager.GetString("CommandUnCheckAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string ContentSizeText {
            get {
                return ResourceManager.GetString("ContentSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Download.
        /// </summary>
        public static string EnumTorrentFilePriorityDontDownload {
            get {
                return ResourceManager.GetString("EnumTorrentFilePriorityDontDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Priority.
        /// </summary>
        public static string EnumTorrentFilePriorityHighPriority {
            get {
                return ResourceManager.GetString("EnumTorrentFilePriorityHighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Priority.
        /// </summary>
        public static string EnumTorrentFilePriorityLowPriority {
            get {
                return ResourceManager.GetString("EnumTorrentFilePriorityLowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Priority.
        /// </summary>
        public static string EnumTorrentFilePriorityNormalPriority {
            get {
                return ResourceManager.GetString("EnumTorrentFilePriorityNormalPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string EnumTorrentServerStateCheck {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string EnumTorrentServerStateChecked {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string EnumTorrentServerStateError {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string EnumTorrentServerStateNone {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string EnumTorrentServerStateQueued {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningAfterChecking.
        /// </summary>
        public static string EnumTorrentServerStateRunningAfterChecking {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateRunningAfterChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string EnumTorrentServerStateStarted {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string EnumTorrentServerStateSuspended {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string EnumTorrentServerStateUploaded {
            get {
                return ResourceManager.GetString("EnumTorrentServerStateUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string FileListText {
            get {
                return ResourceManager.GetString("FileListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path:.
        /// </summary>
        public static string FilePathText {
            get {
                return ResourceManager.GetString("FilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string FileRowContextMenuPriorityGroup {
            get {
                return ResourceManager.GetString("FileRowContextMenuPriorityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte,KB,MB,GB,TB,PB,EB.
        /// </summary>
        public static string FileSizeSuffix {
            get {
                return ResourceManager.GetString("FileSizeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force start.
        /// </summary>
        public static string ForceStartCheckText {
            get {
                return ResourceManager.GetString("ForceStartCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the .torrent file to the server.
        /// </summary>
        public static string MsgAddingCaption {
            get {
                return ResourceManager.GetString("MsgAddingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when you add a .torrent file to the server.
        /// </summary>
        public static string MsgAddingError {
            get {
                return ResourceManager.GetString("MsgAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected category. Use a default category?.
        /// </summary>
        public static string MsgEmptyCategoryText {
            get {
                return ResourceManager.GetString("MsgEmptyCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allow empty category or default categories.
        /// </summary>
        public static string MsgEmptyCategoryTextNotAllow {
            get {
                return ResourceManager.GetString("MsgEmptyCategoryTextNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content to add to the server.
        /// </summary>
        public static string MsgEmptyContentText {
            get {
                return ResourceManager.GetString("MsgEmptyContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading categories.
        /// </summary>
        public static string MsgLoadCategoriesCaption {
            get {
                return ResourceManager.GetString("MsgLoadCategoriesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The categories table has a some record. Delete all records?.
        /// </summary>
        public static string MsgNotEmptyCategorisData {
            get {
                return ResourceManager.GetString("MsgNotEmptyCategorisData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the server.
        /// </summary>
        public static string MsgServerConnection {
            get {
                return ResourceManager.GetString("MsgServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with the server.
        /// </summary>
        public static string MsgServerError {
            get {
                return ResourceManager.GetString("MsgServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connection to the server.
        /// </summary>
        public static string MsgServerOK {
            get {
                return ResourceManager.GetString("MsgServerOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not start download.
        /// </summary>
        public static string NotStartDownloadCheckText {
            get {
                return ResourceManager.GetString("NotStartDownloadCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionLabelText {
            get {
                return ResourceManager.GetString("OptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string OptionRefreshText {
            get {
                return ResourceManager.GetString("OptionRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide downloaded torrents.
        /// </summary>
        public static string OptionShowDownloaded {
            get {
                return ResourceManager.GetString("OptionShowDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project source:.
        /// </summary>
        public static string ProjectSourceHeader {
            get {
                return ResourceManager.GetString("ProjectSourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force start.
        /// </summary>
        public static string RowMenuActionForceStart {
            get {
                return ResourceManager.GetString("RowMenuActionForceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string RowMenuActionPause {
            get {
                return ResourceManager.GetString("RowMenuActionPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove torrent.
        /// </summary>
        public static string RowMenuActionRemove {
            get {
                return ResourceManager.GetString("RowMenuActionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove torrent and data.
        /// </summary>
        public static string RowMenuActionRemoveData {
            get {
                return ResourceManager.GetString("RowMenuActionRemoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string RowMenuActionStart {
            get {
                return ResourceManager.GetString("RowMenuActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string RowMenuActionStop {
            get {
                return ResourceManager.GetString("RowMenuActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ServerLabelText {
            get {
                return ResourceManager.GetString("ServerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        public static string ServerStatusBarCaption {
            get {
                return ResourceManager.GetString("ServerStatusBarCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uTorrent server.
        /// </summary>
        public static string ServerTitleText {
            get {
                return ResourceManager.GetString("ServerTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string ServerTorrentInfoCategory {
            get {
                return ResourceManager.GetString("ServerTorrentInfoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected peers:.
        /// </summary>
        public static string ServerTorrentInfoConnectedPeers {
            get {
                return ResourceManager.GetString("ServerTorrentInfoConnectedPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected seed:.
        /// </summary>
        public static string ServerTorrentInfoConnectedSeed {
            get {
                return ResourceManager.GetString("ServerTorrentInfoConnectedSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded:.
        /// </summary>
        public static string ServerTorrentInfoDownloaded {
            get {
                return ResourceManager.GetString("ServerTorrentInfoDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed:.
        /// </summary>
        public static string ServerTorrentInfoDownloadSpeed {
            get {
                return ResourceManager.GetString("ServerTorrentInfoDownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash:.
        /// </summary>
        public static string ServerTorrentInfoHash {
            get {
                return ResourceManager.GetString("ServerTorrentInfoHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label:.
        /// </summary>
        public static string ServerTorrentInfoLabel {
            get {
                return ResourceManager.GetString("ServerTorrentInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ServerTorrentInfoName {
            get {
                return ResourceManager.GetString("ServerTorrentInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string ServerTorrentInfoSize {
            get {
                return ResourceManager.GetString("ServerTorrentInfoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string ServerTorrentInfoStatus {
            get {
                return ResourceManager.GetString("ServerTorrentInfoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload speed:.
        /// </summary>
        public static string ServerTorrentInfoUploadSpeed {
            get {
                return ResourceManager.GetString("ServerTorrentInfoUploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string ServerTorrentTabFileHeader {
            get {
                return ResourceManager.GetString("ServerTorrentTabFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ServerTorrentTabInfoHeader {
            get {
                return ResourceManager.GetString("ServerTorrentTabInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional settings.
        /// </summary>
        public static string SettingAdditionalGroupTitle {
            get {
                return ResourceManager.GetString("SettingAdditionalGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string SettingsCategoriesColumnCategoryName {
            get {
                return ResourceManager.GetString("SettingsCategoriesColumnCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string SettingsCategoriesColumnComment {
            get {
                return ResourceManager.GetString("SettingsCategoriesColumnComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog index.
        /// </summary>
        public static string SettingsCategoriesColumnTorrentDirectoryListNumber {
            get {
                return ResourceManager.GetString("SettingsCategoriesColumnTorrentDirectoryListNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SettingsCategoriesCommandAdd {
            get {
                return ResourceManager.GetString("SettingsCategoriesCommandAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SettingsCategoriesCommandDelete {
            get {
                return ResourceManager.GetString("SettingsCategoriesCommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from &quot;settings.dat&quot;.
        /// </summary>
        public static string SettingsCategoriesCommandLoadFromFile {
            get {
                return ResourceManager.GetString("SettingsCategoriesCommandLoadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from uTorrent gui server.
        /// </summary>
        public static string SettingsCategoriesCommandLoadFromLink {
            get {
                return ResourceManager.GetString("SettingsCategoriesCommandLoadFromLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string SettingsCategoriesCommandMoveDown {
            get {
                return ResourceManager.GetString("SettingsCategoriesCommandMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string SettingsCategoriesCommandMoveUp {
            get {
                return ResourceManager.GetString("SettingsCategoriesCommandMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string SettingsCategoriesTableTitle {
            get {
                return ResourceManager.GetString("SettingsCategoriesTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uTorrent gui server settings.
        /// </summary>
        public static string SettingsHostGroupTitle {
            get {
                return ResourceManager.GetString("SettingsHostGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string SettingsHostTitle {
            get {
                return ResourceManager.GetString("SettingsHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string SettingsPasswordTitle {
            get {
                return ResourceManager.GetString("SettingsPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SettingsuAddServerPortTitle {
            get {
                return ResourceManager.GetString("SettingsuAddServerPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string SettingsUserTitle {
            get {
                return ResourceManager.GetString("SettingsUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string StateWebUIConnected {
            get {
                return ResourceManager.GetString("StateWebUIConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection....
        /// </summary>
        public static string StateWebUIConnection {
            get {
                return ResourceManager.GetString("StateWebUIConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string StateWebUINotConnected {
            get {
                return ResourceManager.GetString("StateWebUINotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestButtonText {
            get {
                return ResourceManager.GetString("TestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uAdd - add-tools a .torrent file to uTorrent WebUI.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TorrentListCaptionCategory {
            get {
                return ResourceManager.GetString("TorrentListCaptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peers.
        /// </summary>
        public static string TorrentListCaptionConnectedPeers {
            get {
                return ResourceManager.GetString("TorrentListCaptionConnectedPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds.
        /// </summary>
        public static string TorrentListCaptionConnectedSeed {
            get {
                return ResourceManager.GetString("TorrentListCaptionConnectedSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string TorrentListCaptionDownloadedSize {
            get {
                return ResourceManager.GetString("TorrentListCaptionDownloadedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string TorrentListCaptionDownloadSpeed {
            get {
                return ResourceManager.GetString("TorrentListCaptionDownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed, %.
        /// </summary>
        public static string TorrentListCaptionExecutionPercent {
            get {
                return ResourceManager.GetString("TorrentListCaptionExecutionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TorrentListCaptionFilePriority {
            get {
                return ResourceManager.GetString("TorrentListCaptionFilePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string TorrentListCaptionIndex {
            get {
                return ResourceManager.GetString("TorrentListCaptionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string TorrentListCaptionLabel {
            get {
                return ResourceManager.GetString("TorrentListCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TorrentListCaptionName {
            get {
                return ResourceManager.GetString("TorrentListCaptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string TorrentListCaptionRemainingSize {
            get {
                return ResourceManager.GetString("TorrentListCaptionRemainingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string TorrentListCaptionSize {
            get {
                return ResourceManager.GetString("TorrentListCaptionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TorrentListCaptionStatus {
            get {
                return ResourceManager.GetString("TorrentListCaptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        public static string TorrentListCaptionUploadedSize {
            get {
                return ResourceManager.GetString("TorrentListCaptionUploadedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string TorrentListCaptionUploadSpeed {
            get {
                return ResourceManager.GetString("TorrentListCaptionUploadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:.
        /// </summary>
        public static string TorrentNameText {
            get {
                return ResourceManager.GetString("TorrentNameText", resourceCulture);
            }
        }
    }
}
